name: Lint and Test

on: [push, pull_request]

jobs:
  build:
    name: Linting and Testing
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install modules
      run: yarn
    - name: Lint JS
      run: yarn run eslint . --ext .js,.jsx
    - name: Lint HTML
      run: yarn run htmlhint "**/*.html"
    - name: Lint CSS
      run: yarn run stylelint "**/*.css"
    # TODO: Setup after tests are setup
    # - name: Testing
    #   run: yarn run jest