name: Lint and Test
on: push
jobs:
  build:
    name: Linting and Testing
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install modules
      run: yarn
    - name: Linting
      run: yarn run eslint . --ext .js,.jsx
    # TODO: Setup after tests are setup
    # - name: Testing
    #   run: yarn run jest
    - name: Clean up
      run: rm -rf node_modules yarn.lock