name: Lint and Test

on: pull_request

jobs:
  build:
    name: Linting and Testing
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install modules
      run: yarn
    - name: Lint JS
      run: yarn run eslint "source/**"
    - name: Lint HTML
      run: yarn run htmlhint "source/**/*.html"
    - name: Lint CSS
      run: yarn run stylelint "source/**/*.css"
    # TODO: Setup after tests are setup
    # - name: Testing
    #   run: yarn run jest