name: Lint and Test

on: push
jobs:
  lint-test:
    name: Lint and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install modules
        run: npm i
      - name: Check if Prettier was ran
        run: npx prettier --check .
      - name: Lint JS
        run: npx eslint .
      - name: Lint HTML
        run: npx htmlhint "source/**/*.html"
      - name: Lint CSS
        run: npx stylelint "source/**/*.css"
      - name: Test with Cypress
        uses: cypress-io/github-action@v2
        with:
          start: npm start
