name: Documentation

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate Documentation
        uses: andstor/jsdoc-action@v1.2.0
        with:
          source_dir: ./
          recurse: true
          output_dir: ./out
          
