name: Documentation

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Clone Wiki
      run: |
        git config --local user.email "aasthana@ucsd.edu"
        git config --local user.name "anuragasthana"
        git clone git@github.com:jacksonconte/cse110-wi21-group24.wiki.git
    - name: Install modules
      run: yarn
    - name: Run JSDoc to Markdown
      run: yarn run jsdoc2md -f '*' > documentation.md
    - name: Commit Documentation
      run: |
        rm -rf node_modules
        git add .
        git commit -m "Generating documentation"
        git push https://github.com/jacksonconte/cse110-wi21-group24.git.wiki master
          
