name: Documentation

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn
    - name: Run JSDoc to Markdown
      run: yarn run jsdoc2md -f './*.js' -c jsdocconfig.json
    - name: Commit documentation
      run: |
        git config --local user.email "test@github.com"
        git config --local user.name "Github Action Test"
        git add .
        git commit -m "Generating documentation"
        git push
          
