name: Documentation

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn
      - name: Run JSDoc to Markdown
        run: yarn run jsdoc2md -f 'source/**' > ./docs/Documentation.md
      - name: Commit Documentation
        run: |
          git config --local user.name "Documentation Generator"
          rm -rf node_modules
          rm yarn.lock
          git add .
          git commit -m "Generating documentation"
      - name: Push changes # push the output folder to your repo
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          force: true
      - name: Upload Documentation to Wiki
        uses: SwiftDocOrg/github-wiki-publish-action@v1
        with:
          path: "docs"
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
