name: Documentation

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn
    - name: Run JSDoc to Markdown
      run: yarn run jsdoc2md -f './*.js' -c jsdocconfig.json
    - name: Commit documentation
      run: |
        git config --local user.email "test@github.com"
        git config --local user.name "Github Action Test"
        git add ./documentation
        git commit -m "Generating documentation"
    - name: Upload Documentation to Wiki
      uses: SwiftDocOrg/github-wiki-publish-action@v1
      with:
        path: documentation
      env:
        GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          
